# Generated by Django 2.0.5 on 2018-09-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='url',
            field=models.URLField(default='https://www.linparable.org/'),
        ),
    ]
