# Generated by Django 2.0.5 on 2018-09-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0002_topic_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='short_description',
        ),
        migrations.AddField(
            model_name='graphnode',
            name='short_description',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='graphnode',
            name='X',
            field=models.FloatField(default=50),
        ),
        migrations.AlterField(
            model_name='graphnode',
            name='Y',
            field=models.FloatField(default=50),
        ),
        migrations.AlterField(
            model_name='graphnode',
            name='radius',
            field=models.FloatField(default=20),
        ),
    ]
